name: Backend Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_NOLOGO: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: .NET Info
        run: |
          dotnet --info
          dotnet --list-sdks

      - name: Restore
        run: dotnet restore backend/RealEstate.sln

      - name: Unit & Integration Tests (no E2E)
        shell: bash
        run: |
          set -euo pipefail
          dotnet test backend/RealEstate.Tests/RealEstate.Tests.csproj -c Release \
            --logger "trx;LogFileName=unit.trx" | tee backend-unit-output.txt
          dotnet test backend/RealEstate.Tests.Integration/RealEstate.Tests.Integration.csproj -c Release \
            --logger "trx;LogFileName=integration.trx" | tee backend-integration-output.txt

      - name: Upload test console output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backend-test-output
          path: |
            backend-unit-output.txt
            backend-integration-output.txt

      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-integration-results
          path: |
            backend/RealEstate.Tests/TestResults/**/*.trx
            backend/RealEstate.Tests.Integration/TestResults/**/*.trx

